services:
  app:
    image: analytics-api:v2
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db_service:
        condition: service_healthy

    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env.compose
    ports:
      - "${PORT}:8002"
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT} --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
  db_service:
    image: timescale/timescaledb:latest-pg17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

volumes:
  timescaledb_data: